name: Lint

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/asdf-vm/actions
      - name: Install ASDF
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0

      - name: Run lint
        run: scripts/lint.bash
